language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- iojs
- iojs-v1.0.4
script:
- npm run lint
# NOTE: running test instead of cover, to allow low coverage thresholds for now
# - npm run cover
- npm run test
after_success:
# - npm run coveralls
- npm run autodocs
env:
  global:
  - secure: PBbQBujvmahalekuM9mx/dqwsD61CAgnARauTIBkwWjOwoN8ojW+PFP0GehHo3KOqKZB5UtujcrT75Viy0OYqhefo/EmFwH+ViRn9d6Ga47lKBuQ93PyEOFkx7q/Q6eQ2ac3IZESStPF10+uS24CAIdiL60FWuB9/4Jp1+H0s6A=
  - FLAG_PUBLISH_ON_RELEASE: 'true'
  # - DOCUMENT_BRANCH: ${TRAVIS_BRANCH}
  - FLAG_CLEAN_DOCUMENT: 'true'
