language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- iojs
- iojs-v1.0.4
script:
- npm run lint
- npm run cover
after_success:
- npm run coveralls
- npm run autodocs
env:
  global:
  - secure: dsXQADywfJOlPsJe2EHPQBu6OrJRzov36A354yDacSOK7h8wvqUA+PtybKldg+CnhjXJ6imN6GXyTYEwg7Wsr01b579z/tj2D5XpXxurnJP0Y0Av/QRsHhtpbsyogqltg5zO9KFK3O2NBq9f+Yjeh8Op1WU06b0WNz8i5i77MTA=
  - FLAG_CLEAN_DOCUMENT: 'true'
  - DOCUMENT_BRANCH: ${TRAVIS_BRANCH}
