language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- iojs
- iojs-v1.0.4
script:
- npm run lint
# NOTE: running test instead of cover, to allow low coverage thresholds for now
# - npm run cover
- npm run test
after_success:
# - npm run coveralls
- npm run autodocs
env:
  global:
  - secure: XTd8Z5zz7xz0c90XJFLXAbxOOE5h9l+rIQxhy6Mk0LAAD2Fco5/2NGkcqg0RDRJ0uAuvmC9hLhvZbeUC6TuYmBSwcOprq6UZ/G5mh9OjS6SmJgbiPs/rcUqkASa8BlYbBDNrBlcfSyDxIcHVBdaITLMGjCkOqL7Emh+4gFfOuKE=
  - FLAG_CLEAN_DOCUMENT: 'true'
  - DOCUMENT_BRANCH: ${TRAVIS_BRANCH}
